### PR TITLE
Fix and normalize the Javascript HTTP and SDK styles of State Management

### LINKED ISSUE #693: Javascript: State management code is using callbacks even though the function is async, should use await
**Describe the issue**
At the worst there is a bug with race conditions in the code
In the least the code quality could be improved, and there is missing await on `sleep`

As written the `main` function is `async` and supports the ability to await calls that return a `Promise` but yet it uses callbacks.
I thought perhaps this was intentional but after running the cod I am not sure.

Example output using code directly after clone (without change):
```
== APP == 
== APP == > order-processor@1.0.0 start
== APP == > node index.js
== APP == 
== APP == Saving Order:  { orderId: 1 }
== APP == Saving Order:  { orderId: 2 }
== APP == Saving Order:  { orderId: 3 }
== APP == Saving Order:  { orderId: 4 }
== APP == Saving Order:  { orderId: 5 }
== APP == Saving Order:  { orderId: 7 }
== APP == Saving Order:  { orderId: 8 }
== APP == Saving Order:  { orderId: 9 }
== APP == Saving Order:  { orderId: 10 }
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  { orderId: 3 }
== APP == Deleting Order:  { orderId: 3 }
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  { orderId: 9 }
== APP == Deleting Order:  { orderId: 9 }
== APP == Getting Order:  
== APP == Deleting Order:  
== APP == Getting Order:  
== APP == Deleting Order:
```

Notice that all the "saves" are done at once, then later the gets and deletes and some of the gets and deletes are empty.
This is because there is no `await` on the call to sleep so all loops of the function run as fast as possible creating orders, and then their getting and deletion is queued after.  However, those queuing of calls are also not awaited so they may attempt to get an order BEFORE it is actually created resulting in it not being found.

## Adding proper awaits

```
async function main() {
    for(var i = 1; i <= 10; i++) {
        const orderId = i;
        const order = {orderId: orderId};
        const client = new DaprClient(DAPR_HOST, DAPR_HTTP_PORT);
        const STATE_STORE_NAME = "statestore";

        // Save state into the state store
        await client.state.save(STATE_STORE_NAME, [
            {
                key: orderId.toString(),
                value: order
            }
        ]);
        console.log("Saving Order: ", order);

        await sleep(500);
        // Get state from the state store
        var val = await client.state.get(STATE_STORE_NAME, orderId.toString());
        console.log("Getting Order: ", val);

        await sleep(500);

        // Delete state from the state store
        await client.state.delete(STATE_STORE_NAME, orderId.toString());    
        console.log("Deleting Order: ", val);

        await sleep(500);
    }
}
```
Results in the code that the user likely expected to see
```
== APP == 
== APP == > order-processor@1.0.0 start
== APP == > node index.js
== APP == 
== APP == Saving Order:  { orderId: 1 }
== APP == Getting Order:  { orderId: 1 }
== APP == Deleting Order:  { orderId: 1 }
== APP == Saving Order:  { orderId: 2 }
== APP == Deleting Order:  { orderId: 2 }
== APP == Saving Order:  { orderId: 3 }
== APP == Getting Order:  { orderId: 3 }
== APP == Deleting Order:  { orderId: 3 }
== APP == Saving Order:  { orderId: 4 }
== APP == Getting Order:  { orderId: 4 }
== APP == Deleting Order:  { orderId: 4 }
== APP == Saving Order:  { orderId: 5 }
== APP == Getting Order:  { orderId: 5 }
== APP == Deleting Order:  { orderId: 5 }
== APP == Saving Order:  { orderId: 6 }
== APP == Getting Order:  { orderId: 6 }
== APP == Deleting Order:  { orderId: 6 }
== APP == Saving Order:  { orderId: 7 }
== APP == Getting Order:  { orderId: 7 }
== APP == Deleting Order:  { orderId: 7 }
== APP == Saving Order:  { orderId: 8 }
== APP == Getting Order:  { orderId: 8 }
== APP == Deleting Order:  { orderId: 8 }
== APP == Saving Order:  { orderId: 9 }
== APP == Getting Order:  { orderId: 9 }
== APP == Deleting Order:  { orderId: 9 }
== APP == Saving Order:  { orderId: 10 }
== APP == Getting Order:  { orderId: 10 }
== APP == Deleting Order:  { orderId: 10 }
```

All the orders being saved, retrieved, and deleted. sequentially.

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/

**Expected content**
Explained in post above. It's not clear what the expectation is other than sleep should be awaited.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mattmazzola**
# Description

Both the HTTP and SDK tutorials demonstrating State Management using JavaScript had many mistakes and inconsistencies making them poor quality.

As mentioned in those issues there were numerous problems:
- Not using async await
- Not awaiting the `sleep`
- Using function called `start` that didn't actually start anything
- Creating a DaprClient every iteration of the loop instead of once and re-using
- Attempting to use the return value of HTTP save request, but this returns void
- Inconsistency in how data was access from axios response
- Inconsistency in setup of DAPR_HOST and other variables

You can see both tutorials now function with the same output:

image

### Normalization of HTTP and SDK

The purpose of having the HTTP and SDK folders was to show them doing the same thing and how a developer may choose to use the SDK or may user HTTP directly.
The inconsistencies between the two code samples meant that there were many other changes besides merely using the SDK or not which distracts the user from recognizing this.

By removing all the inconsistencies, or normalizing the code it can be seen much more clearly that the ONLY change is the swapping of SDK calls for HTTP requests.

image

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: 
Closes #2495
Closes #2494
Closes #693

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [x] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

File: state_management/javascript/sdk/order-processor/index.js [hunk 1]
```diff
@@ -1,45 +1,41 @@
-import { DaprClient } from 'dapr-client'; 
+import { DaprClient } from 'dapr-client'
 
-const DAPR_HOST = process.env.DAPR_HOST || "http://localhost";
-const DAPR_HTTP_PORT = process.env.DAPR_HTTP_PORT || "3500";
+const DAPR_HOST = process.env.DAPR_HOST ?? "http://localhost"
```
Comment (paulyuk) [inline state_management/javascript/sdk/order-processor/index.js:3]: Nice the ?? handles more falsely cases.

File: state_management/javascript/sdk/order-processor/index.js [hunk 2]
```diff
@@ -1,45 +1,41 @@
...
+        await client.state.save(DAPR_STATE_STORE_NAME, state)
+        console.log("Saving Order: ", order)
 
-        // Get state from the state store
-        var result = client.state.get(STATE_STORE_NAME, orderId.toString());
-        result.then(function(val) {
-            console.log("Getting Order: ", val);
-        });
+        // Get state from a state store
+        const savedOrder = await client.state.get(DAPR_STATE_STORE_NAME, orderId)
```
Comment (paulyuk) [inline state_management/javascript/sdk/order-processor/index.js:26]: agree we should consistently use await

File: state_management/javascript/sdk/order-processor/index.js [hunk 3]
```diff
@@ -1,45 +1,41 @@
...
         // Delete state from the state store
-        client.state.delete(STATE_STORE_NAME, orderId.toString());    
-        result.then(function(val) {
-            console.log("Deleting Order: ", val);
-        });
+        await client.state.delete(DAPR_STATE_STORE_NAME, orderId)
+        console.log("Deleting Order: ", order)
 
-        sleep(5000);
+        await sleep(1000)
```
Comment (paulyuk) [inline state_management/javascript/sdk/order-processor/index.js:33]: good catch

File: state_management/javascript/sdk/order-processor/package.json [hunk 4]
```diff
@@ -5,7 +5,7 @@
     "main": "index.js",
     "type": "module",
     "scripts": {
-        "start": "node index.js",
+        "start": "node .",
```
Comment (paulyuk) [inline state_management/javascript/sdk/order-processor/package.json:8]: Why is this better?  Just so we learn.

**Review by paulyuk — APPROVED** [review]
LGTM.  Really nice contribution and improvement, @mattmazzola Thank you!.  I'd love to make a little style guide with things like use Await instead of and not including .then, etc, removing last ; etc.

**Comment by paulyuk** [comment]
I would love @XavierGeerinck (js maintainer) and @amulyavarote (author) to review too.

File: state_management/javascript/http/order-processor/index.js [hunk 5]
```diff
@@ -1,42 +1,40 @@
...
 async function main() {
-  for(var i = 1; i <= 10; i++) {
-    const orderId = i;
-    const order = {orderId: orderId}; 
-    const state = [{
-      key: orderId.toString(),
-      value: order
-    }];
+  // For each loop, Save order, Get order, and Delete order
+  for (var i = 1; i <= 10; i++) {
```
Comment (XavierGeerinck) [inline state_management/javascript/http/order-processor/index.js:10]: would want to use `let` instead of `var` since the latter is global scoped

File: state_management/javascript/http/order-processor/index.js [hunk 6]
```diff
@@ -1,42 +1,40 @@
...
+    const orderId = i.toString()
+    const order = { orderId }
+    const state = [
+      {
+        key: order.orderId.toString(),
```
Comment (XavierGeerinck) [inline state_management/javascript/http/order-processor/index.js:15]: why not use `orderId` here?

File: state_management/javascript/sdk/order-processor/index.js [hunk 7]
```diff
@@ -1,45 +1,41 @@
-import { DaprClient } from 'dapr-client'; 
+import { DaprClient } from 'dapr-client'
```
Comment (XavierGeerinck) [inline state_management/javascript/sdk/order-processor/index.js:1]: Please use `@dapr/dapr` instead of `dapr-client` as the latter is being deprecated

File: state_management/javascript/http/order-processor/index.js [hunk 8]
```diff
@@ -1,42 +1,40 @@
-import axios from "axios";
+import axios from "axios"
 
-const DAPR_HOST = process.env.DAPR_HOST || "http://localhost";
-const DAPR_HTTP_PORT = process.env.DAPR_HTTP_PORT || "3500";
-const DAPR_STATE_STORE = 'statestore'
+const DAPR_HOST = process.env.DAPR_HOST ?? "http://localhost"
```
Comment (XavierGeerinck) [inline state_management/javascript/http/order-processor/index.js:3]: split protocol from host, use protocol in constructing the url

File: state_management/javascript/sdk/order-processor/index.js (hunk 1 above)
Comment (XavierGeerinck) [inline state_management/javascript/sdk/order-processor/index.js:3]: split protocol from host, use protocol in constructing the url

File: state_management/javascript/sdk/order-processor/index.js [hunk 9]
```diff
@@ -1,45 +1,41 @@
...
+    const client = new DaprClient(DAPR_HOST, DAPR_HTTP_PORT)
+
+    // For each loop, Save order, Get order, and Delete order
+    for (var i = 1; i <= 10; i++) {
+        const orderId = i.toString()
+        const order = { orderId }
+        const state = [
             {
-                key: orderId.toString(),
+                key: order.orderId.toString(),
```
Comment (XavierGeerinck) [inline state_management/javascript/sdk/order-processor/index.js:16]: use orderId instead of order.orderId?

**Review by XavierGeerinck — CHANGES_REQUESTED** [review]

**Comment by XavierGeerinck** [comment]
> I would love @XavierGeerinck (js maintainer) and @amulyavarote (author) to review too.

Added my review on it, thanks for flagging me in it! :) really nice PR

**Comment by amulyavarote** [comment]
> I would love @XavierGeerinck (js maintainer) and @amulyavarote (author) to review too.

Review looks good to me!

File: state_management/javascript/sdk/order-processor/package.json (hunk 4 above)
Comment (mattmazzola) [reply state_management/javascript/sdk/order-processor/package.json:8]: In this package, the `start` command is invoking the same file that is already indicated by the `"main": "index.js"` field of package.json. Using `.` reduces the duplication so if it was changed, you only have to change it one location and not worry about keeping them synchronized.

File: state_management/javascript/sdk/order-processor/index.js (hunk 9 above)
Comment (mattmazzola) [reply state_management/javascript/sdk/order-processor/index.js:32]: Won't fix. It's less robust. See other comment for more details.

File: state_management/javascript/http/order-processor/index.js (hunk 6 above)
Comment (mattmazzola) [reply state_management/javascript/http/order-processor/index.js:30]: It's minor, but it is more robust to use the `orderId` of the order object so it is guruanteed to be the id of the object and not some other ID.  Even though we know `orderId` was used to set the id of the order, this is not guaranteed.

Someone could technically create the order with id then change order id.

Example:
```
let orderId = "1",
const order = { orderId }
orderId = "2"

const state = [
    {
        key: orderId,
        value: order
    }
]
```

This would cause an order which has id "1" to have key "2". The code should make this not possible. Which is why we used the orderId from the order.

File: state_management/javascript/http/order-processor/index.js (hunk 5 above)
Comment (mattmazzola) [reply state_management/javascript/http/order-processor/index.js]: Changed to `let`

File: state_management/javascript/sdk/order-processor/index.js (hunk 7 above)
Comment (mattmazzola) [reply state_management/javascript/sdk/order-processor/index.js]: Changed to use `@dapr/dapr`

File: state_management/javascript/http/order-processor/index.js (hunk 8 above)
Comment (mattmazzola) [reply state_management/javascript/http/order-processor/index.js]: I did split the port from host although I'm not sure if it is done how you expected. I don't see any env vars which indicate protocol.  Because of this, there is complexity introduced using protocol to determine if PORT should be assigned DAPR_HTTP_PORT or DAPR_GRPC_PORT. This could intimidate new users as they would likely choose one protocol for their service and it would be very rare to write an service to support BOTH.

I didn't see any environment variable set which indicated which protocol was intended to be used.
These are the only vars I knew about:
```
DAPR_GRPC_PORT
DAPR_HTTP_PORT
DAPR_METRICS_PORT
```
Is there a var given to the application that specifies protocol?

In my opinion, this request for gRPC is a not appropriate. This PR was about making the samples consistent and runnable. The original tutorials included the protocol with the host.
This is like a new feature to make these samples support gRPC.

File: state_management/javascript/sdk/order-processor/index.js (hunk 1 above)
Comment (mattmazzola) [reply state_management/javascript/sdk/order-processor/index.js]: I split the protocol from host. See other comment for details.

File: state_management/javascript/sdk/order-processor/index.js [hunk 10]
```diff
@@ -1,45 +1,58 @@
...
 async function main() {
-    for(var i = 1; i <= 10; i++) {
-        const orderId = i;
-        const order = {orderId: orderId};
-        const client = new DaprClient(DAPR_HOST, DAPR_HTTP_PORT);
-        const STATE_STORE_NAME = "statestore";
-
-        // Save state into the state store
-        client.state.save(STATE_STORE_NAME, [
+    const host = `${DAPR_PROTOCOL}://${DAPR_HOST}`
```
Comment (XavierGeerinck) [inline state_management/javascript/sdk/order-processor/index.js:24]: You don't need to use the host here as we will automatically do this for you (https://github.com/dapr/js-sdk/blob/master/src/implementation/Client/HTTPClient/HTTPClient.ts#L47) so you can drop the url creation here and just pass `localhost`.


As for which protocol to use, maybe you can just use: 

```javascript
import { DaprClient, CommunicationProtocol } from "@dapr/dapr";

const protocol = (DAPR_PROTOCOL === "http") ? CommunicationProtocol.HTTP : CommunicationProtocol.GRPC;
const client = new DaprClient(host, PORT, protocol); 
```

Comment (mattmazzola) [reply state_management/javascript/sdk/order-processor/index.js]: Ok, I updated to use something similar to your suggestion

- Use `CommunicationProtocolEnum` instead of 'http' string
- Remove protocol from url construction and instead pass protocol to DaprClient constructor
- use lowercase version of variables (port, host, etc) since they were not constants
- Remove `orderId` to avoid confusion about why it wasn't used

Given DAPR_PROTOCOL is non standard and is NOT set automatically by the Dapr CLI like the other env vars we have to assume it will not be set and in that case default both to "http"

### Ideas for Dapr / CLI improvement

Given this determining of which port / env var to use based on protocol is going to be common across all Dapr apps. I think there should be first-class support for this in the Dapr SDK and the Dapr CLI should make DAPR_PROTOCOL standard and set it just like DAPR_GRPC_PORT and DAPR_HTTP_PORT

option | var
--- | ---
--app-protocol http | ? (why is nothing set for this?)
--dapr-http-port 3500 | DAPR_HTTP_PORT
--dapr-grpc-port 6001 | DAPR_GRPC_PORT

**Comment by amulyavarote** [comment]
@mattmazzola Hi! Thanks for this contribution. Can you please take the latest changes, rebase and push the changes? We actually pushed few changes recently to fix the build issues. Pulling and rebasing the latest changes should fix your PR's build issues. Thanks!

**Comment by amulyavarote** [comment]
Other changes look good to me!

**Review by amulyavarote — COMMENTED** [review]
Other changes look good to me!

**Comment by amulyavarote** [comment]
Hi! Can you please fix state management workflows and also DCO?

**Comment by mattmazzola** [comment]
> Hi! Can you please fix state management workflows and also DCO?

No, I don't know what those terms mean.  I thought this would be a simple PR, but this ridiculous. I give up

**Comment by msfussell** [comment]
@mattmazzola - @amulyavarote will work with you to resolve the above. This PR is too good to drop. We really welcome your contribution here and apologize if this is unclear. We will work to make the testing need to be simpler.

**Review by msfussell — APPROVED** [review]
LGTM
