### PR TITLE
#682 APP_PORT not injected into app container

### LINKED ISSUE #684: dapr.io/app_port annotation does not get injected into environment variable in K8s mode
## Expected Behavior
dapr.io/app_port annotation does not set the environment variable APP_PORT in the app container.

APP_PORT environment variable should be set and be accessible from the application container
Applicable quickstarts should be validated in the Kubernetes environment

## Actual Behavior

app_port  is set via kubernetes annotation dapr.io/app_port and accessed via APP_PORT environment variable in the quickstarts. This change was made to relieve the users from having to follow the quickstart documentation and use hard coded port value. [#675 ]

In kubernetes environment, the APP_PORT Environment variable is not being set. [#682]

## Steps to Reproduce the Problem

#682

### PR DESCRIPTION
**Pull request by akhilac1**
Signed-off-by: akhilac1 <chetlapalle.akhila@gmail.com>

# Description

1. Added default value for APP_PORT in case it cannot be fetched from environment variables
2. Updated yaml to include addition of environment variable for APP_PORT [ until the dapr.io/app_port annotation issue is fixed #684  ]
3. Default command to run the app in observability quickstart ALWAYS uses port 5000. Updated quickstarts/tutorials/observability/python/Dockerfile to use python3 app.py as launch command and use specified port

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #682 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] The quickstart code compiles correctly
* [X] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

**Comment by akhilac1** [comment]
@paulyuk @msfussell @berndverst - The ubuntu tutorials are failing due to python app in distributed calculator. This app needs the updated docker image to pass - since the existing docker image uses flask and the app never comes up on 5001. It works on my local test with updated Docker image. My understanding is that test does not build Docker files - rather it is using old Docker file in which case this test would not pass until the image is updated. 
Also am unable to fix the DCO error due to merge conflicts [ added and reverted some code]. Can this be overridden by the maintainer and merged?

**Comment by paulyuk** [comment]
Hi @akhilac1 - thank you for this.  The DCO issue is separate from the Docker build and push to registry.  For DCO I suggest you do every commit via a `git commit -s -p` or at least `-s` as a part of your commit.  This will sign with DCO and pass that.  I will sign it this time.  Also you're right there's a chicken and egg problem here.  The action as written needs the docker images for python, distribute calculator, etc published to GHCR before the tests will pass.  So basically we test these in prod, and rely on the review to decide if we should let it in.  I will do that now.

File: pub_sub/javascript/http/order-processor/index.js [hunk 1]
```diff
@@ -1,11 +1,8 @@
 import express from 'express';
 import bodyParser from 'body-parser';
 
-const APP_PORT = process.env.APP_PORT
-if(!APP_PORT) {
-    console.log('[error]: --app-port is not set. Re-run dapr run with -p or --app-port.\nUsage: https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/\n');
-    process.exit(1);
-}
+const APP_PORT = process.env.APP_PORT || 5001;
```
Comment (paulyuk) [inline pub_sub/javascript/http/order-processor/index.js:4]:
```suggestion
const APP_PORT = process.env.APP_PORT ?? '5001';
```

Prefer we use ?? operator which covers more cases for false that come up in Javascript.  I. believe we want port to be a string too.

File: tutorials/bindings/nodeapp/app.js [hunk 2]
```diff
@@ -13,11 +13,7 @@
 
 const express = require('express');
 const bodyParser = require('body-parser');
-const port = process.env.APP_PORT ;
-if(!port) {
-    console.error('[error]: --app-port is not set. Re-run dapr run with -p or --app-port.\nUsage: https://github.com/dapr/quickstarts/tree/master/tutorials/bindings\n');
-    process.exit(1);
-}
+const port = process.env.APP_PORT || 3000 ;
```
Comment (paulyuk) [inline tutorials/bindings/nodeapp/app.js:16]:
```suggestion
const port = process.env.APP_PORT ?? '3000' ;

```

File: tutorials/distributed-calculator/node/app.js [hunk 3]
```diff
@@ -16,11 +16,7 @@ const bodyParser = require('body-parser');
 const app = express();
 app.use(bodyParser.json());
 const cors = require('cors');
-const port = process.env.APP_PORT ;
-if(!port) {
-    console.error('[error]: --app-port is not set. Re-run dapr run with -p or --app-port.\nUsage: https://github.com/dapr/quickstarts/tree/master/tutorials/distributed-calculator\n');
-    process.exit(1);
-}
+const port = process.env.APP_PORT || 4000 ;
```
Comment (paulyuk) [inline tutorials/distributed-calculator/node/app.js:19]:
```suggestion
const port = process.env.APP_PORT ?? '4000';
```

File: tutorials/distributed-calculator/python/app.py [hunk 4]
```diff
@@ -32,4 +30,4 @@ def multiply():
     print(f"Calculating {operand_one} * {operand_two}", flush=True)
     return jsonify(math.ceil(operand_one * operand_two * 100000)/100000)
 
-app.run(port=appPort)
+app.run(host="0.0.0.0",port=appPort)
```
Comment (paulyuk) [inline tutorials/distributed-calculator/python/app.py:33]: Why do we need "0.0.0.0" host ip?

File: tutorials/hello-world/node/app.js [hunk 5]
```diff
@@ -20,11 +20,7 @@ app.use(express.json());
 const daprPort = process.env.DAPR_HTTP_PORT || 3500;
 const stateStoreName = `statestore`;
 const stateUrl = `http://localhost:${daprPort}/v1.0/state/${stateStoreName}`;
-const port = process.env.APP_PORT ;
-if(!port) {
-    console.error('[error]: --app-port is not set. Re-run dapr run with -p or --app-port.\nUsage: https://github.com/dapr/quickstarts/tree/master/tutorials/hello-world\n');
-    process.exit(1);
-}
+const port = process.env.APP_PORT || 3000;
```
Comment (paulyuk) [inline tutorials/hello-world/node/app.js:23]:
```suggestion
const port = process.env.APP_PORT ?? '3000';
```

File: tutorials/observability/python/app.py [hunk 6]
```diff
@@ -37,4 +35,4 @@ def multiply():
     print(f"Calculating {operand_one} * {operand_two}", flush=True)
     return jsonify(math.ceil(operand_one * operand_two * 100000)/100000)
 
-app.run(port)
+app.run(host="0.0.0.0",port=port)
```
Comment (paulyuk) [inline tutorials/observability/python/app.py:38]: Just checking we need to set host?

**Review by paulyuk — CHANGES_REQUESTED** [review]
Hi - just a few things to look at please.  thank you for updating all this.

File: tutorials/observability/python/app.py (hunk 6 above)
Comment (akhilac1) [reply tutorials/observability/python/app.py:38]: @paulyuk - It is not mandatory. This makes the value being used explicit.

File: tutorials/distributed-calculator/python/app.py (hunk 4 above)
Comment (akhilac1) [reply tutorials/distributed-calculator/python/app.py:33]: @paulyuk - to make the value being used explicit.

File: tutorials/observability/python/app.py (hunk 6 above)
Comment (paulyuk) [reply tutorials/observability/python/app.py:38]: @akhilac1 ok, I just want to make sure that still works in a few environments that might have benefited from defaults.  E.g. have you tried this on Windows, WSL, and Mac?  have you tried with Ipv6? 

The other way to ask is are we fixing a problem with this change?  if not we might have lower risk of regressions by not making the change, since this has worked this way for a few years.

Comment (paulyuk) [reply tutorials/observability/python/app.py:38]: That said, I'll take it and let's monitor

**Review by paulyuk — APPROVED** [review]
LGTM

**Comment by paulyuk** [comment]
Tests are all clean except for Validate Tutorials which is expected.  I'm merging.
